### ISSUE TITLE
能否开源一下后端项目

### ISSUE THREAD

**Issue by QCCS** [jigsaw-china/unnue-nuxt#1]

**Comment by jigsaw-china** [comment]
可以，近期我会更新一下，感谢支持。

**Comment by QCCS** [comment]
多谢




------------------ 原始邮件 ------------------
发件人: "jigsaw"<notifications@github.com>; 
发送时间: 2019年5月27日(星期一) 下午4:19
收件人: "jigsaw-china/unnue-nuxt"<unnue-nuxt@noreply.github.com>; 
抄送: "新前朝楚水"<2565510046@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [jigsaw-china/unnue-nuxt] 能否开源一下后端项目 (#1)




可以，近期我会更新一下，感谢支持。
